"""D15 / B2.151 follow-up: book maps → (1) CoreRpg resource p1-book-maps.yml (builder input),
(2) runs yml rooms / doors / points / boss / event for the switched maps, (3) DP dungeon options + config.
python3 gen.py q01 q02 ...   (maps to switch; q05 is hand-made in P1MapLayout.spireV1 and only written to the yml)"""
import json, re, sys, os
from book import parse, extra_points, ROOT
ROOFED = {'q02', 'q03'}
LOW_GUARD = {'q05': ['R2', 'RB']}
DATE = '2026-10-02'


def yml_list(v):
    return json.dumps(v).replace('"', '')


def resource(maps):
    lines = ['# GENERATED by tools/p1map/gen.py from docs/design-ember-v1.0-P1.md ch. 11-17 (do not edit by hand)', 'maps:']
    for k, m in maps.items():
        lines.append(f'  {k}:')
        lines.append(f'    name: {m["name"]}')
        lines.append(f'    template: {m["template"]}')
        lines.append(f'    base: {m["base"]}')
        lines.append(f'    roofed: {"true" if k in ROOFED else "false"}')
        lines.append(f'    low_guard: {yml_list(LOW_GUARD.get(k, []))}')
        lines.append(f'    spawn: {yml_list(m["spawn"])}')
        lines.append('    rooms:')
        for r in m['rooms']:
            lines.append('      - {id: %s, x0: %d, x1: %d, z0: %d, z1: %d, f: %d, h: %d}' % (r['id'], r['x0'], r['x1'], r['z0'], r['z1'], r['f'], r['h']))
        lines.append('    corridors:')
        for c in m['corridors']:
            lines.append('      - {id: %s, nodes: %s}' % (c['id'], yml_list(c['nodes'])))
    return '\n'.join(lines) + '\n'


def rooms_block(m):
    R = {r['id']: r for r in m['rooms']}
    door_of = {'R1': 'G2', 'R2': 'G3', 'R3': 'GB'}
    out = ['    rooms:']
    for rid in ('R1', 'R2', 'R3'):
        r = R[rid]; six = m['points'][rid]
        extra = extra_points(r, six, list(m['doors'].values()))
        pts = six + extra
        out.append(f'      {rid.lower()}:')
        out.append(f'        label: {r["label"]}')
        out.append(f'        trigger: {yml_list([r["x0"], r["f"] - 1, r["z0"], r["x1"], r["f"] + 4, r["z1"]])}')
        out.append(f'        points: {yml_list(pts)}')
        out.append(f'        door: {yml_list(m["doors"][door_of[rid]])}')
    return out


def patch_runs(text, k, m):
    q = text.index(f'\n  {k}:\n') + 1
    nxt = re.search(r'\n  q0\d:\n', text[q + 5:])
    e = q + 5 + nxt.start() + 1 if nxt else len(text)
    blk = text[q:e]
    lines = blk.split('\n')
    R = {r['id']: r for r in m['rooms']}
    old_rooms = {}
    # keep a / b compositions per room from the existing block
    cur = None
    for ln in lines:
        mm = re.match(r'^      (r[1-3]):$', ln)
        if mm: cur = mm.group(1); old_rooms[cur] = {}; continue
        if cur and re.match(r'^        [ab]: ', ln): old_rooms[cur][ln.strip()[0]] = ln
        if re.match(r'^    \S', ln): cur = None
    res, skip = [], False
    i = 0
    while i < len(lines):
        ln = lines[i]
        top = re.match(r'^    ([a-z_]+):', ln)
        if top:
            key = top.group(1)
            skip = False
            if key in ('clear', 'links', 'rails'):
                skip = True; i += 1
                # drop the comment lines right above as well
                while res and res[-1].startswith('    #'): res.pop()
                continue
            if key == 'template': ln = f'    template: {m["template"]}'
            if key == 'map_version': ln = f'    map_version: {m["template"]}@d15-{DATE}'
            if key == 'spawn':
                sx, sy, sz = m['spawn']
                while res and res[-1].startswith('    #'): res.pop()
                res.append(f'    # D15: book ch. {10 + int(k[1:])} walkable white box ({m["template"]}, /corerpg p1 mapbuild {k})')
                res.append(f'    spawn: {yml_list(m["spawn"])}')
                res.append(f'    spread: {yml_list([[sx - 2, sy, sz], [sx + 2, sy, sz]])}')
                i += 1
                continue
            if key == 'spread': i += 1; continue
            if key == 'rooms':
                rb = rooms_block(m)
                # re-insert a / b
                outb = []
                for x in rb:
                    outb.append(x)
                    mm = re.match(r'^        door: ', x)
                    if mm:
                        rid = outb[-5].strip().rstrip(':')
                        for ab in ('a', 'b'):
                            if ab in old_rooms.get(rid, {}): outb.append(old_rooms[rid][ab])
                res.extend(outb)
                i += 1
                while i < len(lines) and (lines[i].startswith('      ') or lines[i].startswith('    #') and False): i += 1
                continue
        if skip:
            if ln.startswith('      ') or ln.startswith('    #') or ln.strip() == '':
                if ln.strip() == '': skip = False; res.append(ln)
                i += 1; continue
            skip = False
        res.append(ln); i += 1
    blk = '\n'.join(res)
    rb = R['RB']
    bx, by, bz = m['boss']
    blk = re.sub(r'(\n      at: )\[[^\]]*\]\n      area: \[[^\]]*\]\n', lambda _: f'\n      at: {yml_list(m["boss"])}\n      area: {yml_list([rb["x0"], rb["f"] - 1, rb["z0"], rb["x1"], rb["f"] + min(rb["h"], 10), rb["z1"]])}\n      wait_in_area: true\n', blk, count=1)
    # boss adds (Q03): two points left / right of the boss
    blk = re.sub(r'(\n        # book: boss x±8[^\n]*)?(\n        points: )\[\[[^\n]*\]\](\n    event:)', lambda mm: f'\n        # book: boss x±8, z−4 (D15 hall){mm.group(2)}{yml_list([[bx - 8, by, bz - 4], [bx + 8, by, bz - 4]])}{mm.group(3)}', blk)
    E = R['E']
    blk = re.sub(r'\n    event:\n      after: \S+\n      anchor: \[[^\]]*\]\n      area: \[[^\]]*\]', f'\n    event:\n      after: r2\n      anchor: {yml_list(m["event"])}\n      area: {yml_list([E["x0"], E["f"] - 1, E["z0"], E["x1"], E["f"] + 6, E["z1"]])}', blk)
    return text[:q] + blk + text[e:]


def patch_dp(k, m):
    d = 'EmberQ' + k[1:]
    p = os.path.join(ROOT, 'plugins/DungeonPlus/dungeon', d, 'option.yml')
    s = open(p, encoding='utf-8').read()
    sx, sy, sz = m['spawn']
    s = re.sub(r'\$setmap\{name=[a-z_]+\}', '$setmap{name=%s}' % m['template'], s)
    s = re.sub(r'\$setspawn\{location=[-\d,]+\}', '$setspawn{location=%d,%d,%d}' % (sx, sy, sz), s)
    s = re.sub(r'\$teleport\{location=[-\d,]+;defspawn=true\}', '$teleport{location=%d,%d,%d;defspawn=true}' % (sx, sy, sz), s)
    s = re.sub(r'复用 \S+ 地图模板；', '地图 %s（D15：书第 %d 章白盒，可步行，首领厅按书尺寸）；' % (m['template'], 10 + int(k[1:])), s, count=1)
    s = '\n'.join(l for l in s.split('\n') if not (l.startswith('# ') and ('clear:' in l or 'rails' in l or '告示牌只在实例内' in l)))
    open(p, 'w', encoding='utf-8').write(s)
    c = os.path.join(ROOT, 'plugins/DungeonPlus/config.yml')
    s = open(c, encoding='utf-8').read()
    s = re.sub(r'\n(\s*# [^\n]*\n)?\s*"%s": 1' % d, '', s, count=1)
    anchor = '  # ember-v1.0-P1 B2.151'
    s = s.replace(anchor, '  %s:\n    "%s": 1\n' % (m['template'], d) + anchor, 1)
    open(c, 'w', encoding='utf-8').write(s)


if __name__ == '__main__':
    maps = parse()
    open(os.path.join(ROOT, 'CoreRpg/src/main/resources/p1-book-maps.yml'), 'w', encoding='utf-8').write(resource(maps))
    runs = [os.path.join(ROOT, 'CoreRpg/src/main/resources/ember-v1-runs.yml'), os.path.join(ROOT, 'plugins/CoreRpg/ember-v1-runs.yml')]
    t = open(runs[0], encoding='utf-8').read()
    for k in sys.argv[1:]:
        t = patch_runs(t, k, maps[k])
        patch_dp(k, maps[k])
    for p in runs: open(p, 'w', encoding='utf-8').write(t)
