const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({ host:'127.0.0.1', port:25565, username:'RpgBot', version:'1.12.2', auth:'offline' })
bot.on('message', m => console.log('[chat]', m.toString()))
const wait = ms => new Promise(r => setTimeout(r, ms))
async function chat(c){ console.log('[cmd]', c); bot.chat(c); await wait(1000) }
bot.once('spawn', async () => {
  await wait(2000)
  await chat('/ni give RpgBot ticket_ember_daily 5')
  await wait(1500)
  console.log('[inv]', bot.inventory.items().map(i => ({n:i.name, dn:i.customName, c:i.count})).filter(x => x.dn || x.n.includes('paper') || x.n.includes('ticket')))
  await chat('/dp start EmberDaily')
  await wait(5000)
  console.log('[pos]', bot.entity.position)
  await chat('/dp leave')
  await wait(1500)
  console.log('[pos2]', bot.entity.position)
  process.exit(0)
})
bot.on('kicked', r => { console.error(r); process.exit(1) })
setTimeout(() => process.exit(2), 50000)
