const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({host:'127.0.0.1',port:25565,username:'RpgBot',auth:'offline',version:'1.12.2'})
const chat=[]; bot.on('message',m=>{const s=m.toString();chat.push(s);console.log('[chat]',s)})
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
bot.once('spawn', async()=>{
  await sleep(800)
  bot.chat('/papi reload'); await sleep(3000)
  bot.chat('/papi list'); await sleep(1500)
  bot.chat('/papi parse me %player_name%'); await sleep(800)
  bot.chat('/papi parse me %server_name%'); await sleep(800)
  bot.chat('/papi parse me %vault_eco_balance%'); await sleep(800)
  console.log('FILTER', chat.join(' || '))
  bot.quit(); setTimeout(()=>process.exit(0),400)
})
bot.on('error',e=>{console.error(e);process.exit(1)})
bot.on('kicked',r=>{console.error(r);process.exit(1)})
setTimeout(()=>process.exit(2),30000)
